#!/usr/bin/env python3
"""
QA preview script — generates static HTML from content.json and serves it.
Also writes config/config.php with the provided admin password hash.
Run: python3 qa_preview.py
"""

import json
import hashlib
import bcrypt
import html
import os
import http.server
import threading
import webbrowser
import time

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ── 1. Generate and write admin password hash ─────────────────────────────────
PASSWORD = 'projectdilbachao'
sha256   = hashlib.sha256(PASSWORD.encode()).hexdigest()
bchash   = bcrypt.hashpw(sha256.encode(), bcrypt.gensalt(rounds=12)).decode()

config_path = os.path.join(BASE_DIR, 'config', 'config.php')
with open(config_path, 'w') as f:
    f.write(f"<?php\n// Auto-generated by qa_preview.py — replace with your own hash in production.\ndefine('ADMIN_PASSWORD_HASH', '{bchash}');\n")
print(f"✓ config/config.php written with hash for '{PASSWORD}'")

# ── 2. Load content ───────────────────────────────────────────────────────────
with open(os.path.join(BASE_DIR, 'data', 'content.json')) as f:
    C = json.load(f)

def esc(val, default=''):
    return html.escape(str(val) if val is not None else default)

def c(section, key, default=''):
    return esc(C.get(section, {}).get(key, default))

def section_attrs(section):
    sec  = C.get(section, {})
    bg   = esc(sec.get('bg_color', '#0a0a0a'))
    hidden = 'false' if sec.get('visible', True) else 'true'
    return f'data-section="{section}" style="background-color:{bg}" data-bg-color="{bg}" data-hidden="{hidden}"'

def section_bg(section):
    return esc(C.get(section, {}).get('bg_color', '#0a0a0a'))

# ── 3. Render HTML ────────────────────────────────────────────────────────────
def render():
    cards = C['features']['cards']
    card_classes = ['', '', 'emergency']
    features_html = ''
    for i, card in enumerate(cards):
        cls = card_classes[i] if i < len(card_classes) else ''
        delay = i * 0.15
        features_html += f'''
      <div class="feature-card fade-up" style="transition-delay:{delay}s">
        <div class="card-icon-wrap {cls}">
          <img class="card-icon"
               src="{esc(card.get('icon','assets/images/icon-heart.svg'))}"
               alt="{esc(card.get('title',''))}"
               data-image-key="features.cards.{i}.icon">
        </div>
        <h3 class="card-title" data-editable="text" data-key="cards.{i}.title">{esc(card.get('title',''))}</h3>
        <p class="card-description" data-editable="text" data-key="cards.{i}.description">{esc(card.get('description',''))}</p>
      </div>'''

    steps_html = ''
    for i, step in enumerate(C['how_it_works']['steps']):
        num = esc(step.get('number', f'{i+1:02d}'))
        steps_html += f'''
      <div class="step-item fade-up">
        <div class="step-content">
          <p class="step-number">{num}</p>
          <h3 class="step-title" data-editable="text" data-key="steps.{i}.title">{esc(step.get('title',''))}</h3>
          <p class="step-description" data-editable="text" data-key="steps.{i}.description">{esc(step.get('description',''))}</p>
        </div>
        <div class="step-image-wrap">
          <img src="{esc(step.get('image','assets/images/step-placeholder.svg'))}"
               alt="{esc(step.get('title',''))}"
               data-image-key="how_it_works.steps.{i}.image">
        </div>
      </div>'''

    for_html = ''
    for side in ['left', 'right']:
        side_data = C['who_its_for'].get(side, {})
        for_html += f'''
      <div class="for-card fade-up">
        <img class="for-card-image"
             src="{esc(side_data.get('image','assets/images/person-placeholder.svg'))}"
             alt="{esc(side_data.get('title',''))}"
             data-image-key="who_its_for.{side}.image">
        <div class="for-card-body">
          <h3 class="for-card-title" data-editable="text" data-key="{side}.title">{esc(side_data.get('title',''))}</h3>
          <p class="for-card-description" data-editable="text" data-key="{side}.description">{esc(side_data.get('description',''))}</p>
        </div>
      </div>'''

    specs_html = ''
    for i, row in enumerate(C['specs']['rows']):
        specs_html += f'''
      <div class="spec-row">
        <span class="spec-label" data-editable="text" data-key="rows.{i}.label">{esc(row.get('label',''))}</span>
        <span class="spec-value" data-editable="text" data-key="rows.{i}.value">{esc(row.get('value',''))}</span>
      </div>'''

    socials_html = ''
    footer = C.get('footer', {})
    if footer.get('social_twitter'):
        socials_html += f'<a href="{esc(footer["social_twitter"])}" target="_blank" rel="noopener">Twitter</a>'
    if footer.get('social_instagram'):
        socials_html += f'<a href="{esc(footer["social_instagram"])}" target="_blank" rel="noopener">Instagram</a>'
    if footer.get('social_linkedin'):
        socials_html += f'<a href="{esc(footer["social_linkedin"])}" target="_blank" rel="noopener">LinkedIn</a>'

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="HeartGuard — The smart watch built for heart disease patients and athletes.">
  <title>HeartGuard — Your Heart. Protected.</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>

<!-- Admin Bar -->
<div class="admin-bar" id="admin-bar">
  <span class="admin-bar-label">ADMIN MODE — EDITING</span>
  <div class="admin-bar-actions">
    <button class="admin-btn" id="admin-save">Save All</button>
    <button class="admin-btn" id="admin-logout">Logout</button>
  </div>
</div>

<!-- Login Modal -->
<div class="modal-overlay" id="login-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title">
  <div class="modal-box">
    <p class="modal-title" id="modal-title">Admin Access</p>
    <p class="modal-subtitle">Enter your password to edit this page.</p>
    <form id="login-form">
      <input class="modal-input" type="password" id="admin-password" placeholder="Password" autocomplete="current-password" required>
      <p class="modal-error" id="login-error" role="alert"></p>
      <button class="btn-primary" type="submit" style="width:100%">Sign In</button>
    </form>
  </div>
</div>

<div class="admin-toast" id="admin-toast" role="status"></div>

<!-- Navbar -->
<nav class="navbar" id="navbar">
  <a class="nav-brand" href="#hero">
    <img src="{c('navbar','logo','assets/images/logo-placeholder.svg')}" alt="{c('navbar','site_name','HeartGuard')} logo" data-image-key="navbar.logo">
    <span data-editable="text" data-key="site_name" data-section-ref="navbar">{c('navbar','site_name','HeartGuard')}</span>
  </a>
  <ul class="nav-links" id="nav-links">
    <li><a href="#features">Features</a></li>
    <li><a href="#how-it-works">How It Works</a></li>
    <li><a href="#who-its-for">Who It&apos;s For</a></li>
    <li><a href="#story">Story</a></li>
    <li><a href="#specs">Specs</a></li>
    <li><a href="#contact">Contact</a></li>
  </ul>
  <div class="nav-right">
    <button class="admin-lock" id="admin-lock" title="Admin access" aria-label="Admin login">🔒</button>
    <button class="hamburger" id="hamburger" aria-label="Toggle menu" aria-expanded="false">
      <span></span><span></span><span></span>
    </button>
  </div>
</nav>

<!-- Hero -->
<section id="hero" class="hero" {section_attrs('hero')}>
  <div class="section-toolbar" role="toolbar">
    <button class="toolbar-btn toolbar-image" data-image-target="hero.watch_image" title="Swap watch image">🖼</button>
    <input class="toolbar-color" type="color" value="{section_bg('hero')}" title="Background color">
    <button class="toolbar-btn toolbar-visibility" title="Toggle visibility">👁</button>
  </div>
  <div class="hero-glow"></div>
  <div class="hero-content container">
    <h1 class="hero-headline" data-editable="text" data-key="headline">{c('hero','headline','Your Heart. Protected.')}</h1>
    <p class="hero-subheadline" data-editable="text" data-key="subheadline">{c('hero','subheadline')}</p>
    <a href="#features" class="btn-primary" data-editable="text" data-key="cta_text">{c('hero','cta_text','Learn More')}</a>
    <div class="hero-image-wrap">
      <img class="hero-watch" src="{c('hero','watch_image','assets/images/watch-placeholder.svg')}" alt="HeartGuard smart watch" data-image-key="hero.watch_image">
    </div>
  </div>
</section>

<!-- Features -->
<section id="features" class="section-pad" {section_attrs('features')}>
  <div class="section-toolbar" role="toolbar">
    <input class="toolbar-color" type="color" value="{section_bg('features')}" title="Background color">
    <button class="toolbar-btn toolbar-visibility" title="Toggle visibility">👁</button>
  </div>
  <div class="container">
    <div class="section-header fade-up">
      <p class="section-label">What It Does</p>
      <h2 class="section-title" data-editable="text" data-key="section_title">{c('features','section_title','Features')}</h2>
    </div>
    <div class="features-grid">{features_html}</div>
  </div>
</section>

<!-- How It Works -->
<section id="how-it-works" class="section-pad" {section_attrs('how_it_works')}>
  <div class="section-toolbar" role="toolbar">
    <input class="toolbar-color" type="color" value="{section_bg('how_it_works')}" title="Background color">
    <button class="toolbar-btn toolbar-visibility" title="Toggle visibility">👁</button>
  </div>
  <div class="container">
    <div class="section-header fade-up">
      <p class="section-label">The Process</p>
      <h2 class="section-title" data-editable="text" data-key="section_title">{c('how_it_works','section_title','How It Works')}</h2>
    </div>
    <div class="steps-list">{steps_html}</div>
  </div>
</section>

<!-- Who It's For -->
<section id="who-its-for" class="section-pad" {section_attrs('who_its_for')}>
  <div class="section-toolbar" role="toolbar">
    <input class="toolbar-color" type="color" value="{section_bg('who_its_for')}" title="Background color">
    <button class="toolbar-btn toolbar-visibility" title="Toggle visibility">👁</button>
  </div>
  <div class="container">
    <div class="section-header fade-up">
      <p class="section-label">Built For You</p>
      <h2 class="section-title" data-editable="text" data-key="section_title">{c('who_its_for','section_title',"Who It&apos;s For")}</h2>
    </div>
    <div class="for-grid">{for_html}</div>
  </div>
</section>

<!-- Story -->
<section id="story" class="section-pad" {section_attrs('story')}>
  <div class="section-toolbar" role="toolbar">
    <input class="toolbar-color" type="color" value="{section_bg('story')}" title="Background color">
    <button class="toolbar-btn toolbar-visibility" title="Toggle visibility">👁</button>
  </div>
  <div class="container">
    <div class="section-header fade-up">
      <p class="section-label">Our Origin</p>
      <h2 class="section-title" data-editable="text" data-key="section_title">{c('story','section_title','Why HeartGuard Exists')}</h2>
    </div>
    <div class="story-content">
      <p class="story-narrative fade-up" data-editable="text" data-key="narrative">{c('story','narrative')}</p>
      <div class="story-quote fade-up">
        <blockquote data-editable="text" data-key="quote">"{c('story','quote')}"</blockquote>
        <cite data-editable="text" data-key="quote_author">— {c('story','quote_author')}</cite>
      </div>
    </div>
  </div>
</section>

<!-- Specs -->
<section id="specs" class="section-pad" {section_attrs('specs')}>
  <div class="section-toolbar" role="toolbar">
    <input class="toolbar-color" type="color" value="{section_bg('specs')}" title="Background color">
    <button class="toolbar-btn toolbar-visibility" title="Toggle visibility">👁</button>
  </div>
  <div class="container">
    <div class="section-header fade-up">
      <p class="section-label">Under The Hood</p>
      <h2 class="section-title" data-editable="text" data-key="section_title">{c('specs','section_title','Technical Specs')}</h2>
    </div>
    <div class="specs-grid fade-up">{specs_html}</div>
  </div>
</section>

<!-- Contact -->
<section id="contact" class="section-pad" {section_attrs('contact')}>
  <div class="section-toolbar" role="toolbar">
    <input class="toolbar-color" type="color" value="{section_bg('contact')}" title="Background color">
    <button class="toolbar-btn toolbar-visibility" title="Toggle visibility">👁</button>
  </div>
  <div class="container">
    <div class="contact-inner fade-up">
      <h2 class="contact-title" data-editable="text" data-key="section_title">{c('contact','section_title','Get In Touch')}</h2>
      <p class="contact-description" data-editable="text" data-key="description">{c('contact','description')}</p>
      <a class="btn-primary" href="mailto:{c('contact','email','hello@heartguard.com')}" data-editable="text" data-key="cta_text" id="contact-cta">{c('contact','cta_text','Contact Us')}</a>
    </div>
  </div>
</section>

<!-- Footer -->
<footer {section_attrs('footer')}>
  <div class="section-toolbar" role="toolbar">
    <input class="toolbar-color" type="color" value="{section_bg('footer')}" title="Background color">
    <button class="toolbar-btn toolbar-visibility" title="Toggle visibility">👁</button>
  </div>
  <div class="footer-inner">
    <div class="footer-brand">
      <img src="{c('footer','logo','assets/images/logo-placeholder.svg')}" alt="{c('footer','site_name','HeartGuard')}" data-image-key="footer.logo">
      <span data-editable="text" data-key="site_name">{c('footer','site_name','HeartGuard')}</span>
    </div>
    <p class="footer-copy" data-editable="text" data-key="copyright">{c('footer','copyright','© 2026 HeartGuard. All rights reserved.')}</p>
    <div class="footer-socials">{socials_html}</div>
  </div>
</footer>

<script src="assets/js/main.js"></script>
<script src="assets/js/admin.js"></script>
</body>
</html>'''

# Write the static preview
preview_html = os.path.join(BASE_DIR, 'preview.html')
with open(preview_html, 'w') as f:
    f.write(render())
print("✓ preview.html rendered")

# ── 4. Intercept API calls for QA (inline JS patch) ──────────────────────────
# Read preview.html and patch admin.js API calls to use a fake in-memory backend
# so the admin login works in the static preview without PHP.
with open(preview_html) as f:
    html_content = f.read()

# Inject a mock API layer before admin.js loads
mock_api = f"""
<script>
// QA MOCK: intercepts fetch() calls to api/ endpoints so admin mode works without PHP
const QA_BCRYPT_HASH = '{bchash}';
let qaSession = false;

const _origFetch = window.fetch;
window.fetch = async function(url, opts) {{
  const u = typeof url === 'string' ? url : url.toString();

  // Session check
  if (u.includes('api/auth.php') && (!opts || opts.method === 'GET' || !opts.method)) {{
    if (u.includes('logout')) {{ qaSession = false; return jsonResp({{success: true}}); }}
    return jsonResp({{authenticated: qaSession}});
  }}

  // Login
  if (u.includes('api/auth.php') && opts && opts.method === 'POST') {{
    const body = JSON.parse(opts.body);
    // Use SubtleCrypto to SHA-256 the received hash again? No — received IS the sha256.
    // We just check it matches our pre-computed sha256 for QA.
    const expectedSha256 = await sha256('{PASSWORD}');
    if (body.password === expectedSha256) {{
      qaSession = true;
      return jsonResp({{success: true}});
    }}
    return jsonResp({{success: false, message: 'Invalid password'}}, 401);
  }}

  // Save content — accept and confirm (no real file write in static preview)
  if (u.includes('api/save-content.php')) {{
    if (!qaSession) return jsonResp({{success: false, message: 'Unauthorized'}}, 403);
    console.log('[QA] save-content called — no-op in static preview');
    return jsonResp({{success: true}});
  }}

  // Upload — reject with helpful message in static preview
  if (u.includes('api/upload-image.php')) {{
    return jsonResp({{success: false, message: 'Image upload needs PHP server — not available in QA preview'}}, 400);
  }}

  return _origFetch(url, opts);
}};

async function sha256(msg) {{
  const buf = new TextEncoder().encode(msg);
  const hash = await crypto.subtle.digest('SHA-256', buf);
  return Array.from(new Uint8Array(hash)).map(b => b.toString(16).padStart(2,'0')).join('');
}}

function jsonResp(data, status=200) {{
  return new Response(JSON.stringify(data), {{
    status, headers: {{'Content-Type': 'application/json'}}
  }});
}}
</script>
"""

html_content = html_content.replace('<script src="assets/js/main.js"></script>',
    mock_api + '<script src="assets/js/main.js"></script>')
with open(preview_html, 'w') as f:
    f.write(html_content)
print("✓ QA mock API injected (admin login works without PHP)")

# ── 5. Serve and open ─────────────────────────────────────────────────────────
PORT = 8765

class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=BASE_DIR, **kwargs)
    def log_message(self, fmt, *args):
        pass  # quiet

def start_server():
    server = http.server.HTTPServer(('localhost', PORT), Handler)
    server.serve_forever()

t = threading.Thread(target=start_server, daemon=True)
t.start()
print(f"✓ Server running at http://localhost:{PORT}/preview.html")
print(f"\n  Admin password: {PASSWORD}")
print(f"  Click 🔒 in the navbar → enter the password above\n")

webbrowser.open(f'http://localhost:{PORT}/preview.html')
print("✓ Browser opened. Press Ctrl+C to stop the server when done.\n")

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    print("\nServer stopped.")
